In [7]:
import pandas as pd

In [8]:
classes = pd.read_excel("./lsm_dataset/MSLwords1/classes.xlsx")

In [10]:
classes.head()

   Class number           Word    grouping
0             1    Good morning  Greetings
1             2  Good afternoon        NaN
2             3      Good night        NaN
3             4       Thank you        NaN
4             5          Please        NaN

In [13]:
classes = classes.drop('grouping', axis=1)
classes.head()

   Class number           Word
0             1    Good morning
1             2  Good afternoon
2             3      Good night
3             4       Thank you
4             5          Please

In [14]:
classes.to_csv('./lsm_dataset/MSLwords1/clases.csv', index=False)